// == 苹果推送服务及基础网络 (Apple Push & CDN) ==
HOST-SUFFIX, push.apple.com, direct
HOST-SUFFIX, akadns.net, direct
HOST-KEYWORD, apple.com.edgekey.net, direct

// 苹果服务 IPv4 网段
IP-CIDR, 17.249.0.0/16, direct, no-resolve
IP-CIDR, 17.252.0.0/16, direct, no-resolve
IP-CIDR, 17.57.144.0/22, direct, no-resolve
IP-CIDR, 17.188.128.0/18, direct, no-resolve
IP-CIDR, 17.188.20.0/23, direct, no-resolve

// 苹果服务 IPv6 网段
IP6-CIDR, 2620:149:a44::/48, direct, no-resolve
IP6-CIDR, 2403:300:a42::/48, direct, no-resolve
IP6-CIDR, 2403:300:a51::/48, direct, no-resolve
IP6-CIDR, 2a01:b740:a42::/48, direct, no-resolve
