# → 苹果推送机制
# Apple Intelligence / Siri / 推送及相关服务
HOST, identity.apple.com
HOST-SUFFIX, akadns.net
HOST-SUFFIX, push.apple.com
HOST-SUFFIX, apple-cloudkit.com
HOST-SUFFIX, apple-relay.akamaized.net 
HOST-SUFFIX, apple-relay.apple.com
HOST-SUFFIX, apple-relay.cloudflare.com
HOST-SUFFIX, apple-relay.fastly-edge.com
HOST-SUFFIX, apple-relay.mask.apple-dns.net
HOST-KEYWORD, apple.com.edgekey.net
# IP 规则
IP-CIDR, 17.188.128.0/18,  no-resolve
IP-CIDR, 17.188.20.0/23,  no-resolve
IP-CIDR, 17.249.0.0/16,  no-resolve
IP-CIDR, 17.252.0.0/16,  no-resolve
IP-CIDR, 17.57.144.0/22, no-resolve
# IPv6 规则
IP6-CIDR, 2403:300:a42::/48,  no-resolve
IP6-CIDR, 2403:300:a51::/48,  no-resolve
IP6-CIDR, 2620:149:a44::/48, no-resolve
IP6-CIDR, 2a01:b740:a42::/48, no-resolve
