# 本地/局域网地址 (对应 clashscript 仓库 LocalAreaNetwork.list)
# 参考: https://en.wikipedia.org/wiki/Reserved_IP_addresses

HOST-SUFFIX, ip6-localhost, direct
HOST-SUFFIX, ip6-loopback, direct
HOST-SUFFIX, lan, direct
HOST-SUFFIX, local, direct
HOST-SUFFIX, localhost, direct
HOST-SUFFIX, orb.local, direct
IP-CIDR, 0.0.0.0/8, direct, no-resolve
IP-CIDR, 10.0.0.0/8, direct, no-resolve
IP-CIDR, 100.64.0.0/10, direct, no-resolve
IP-CIDR, 127.0.0.0/8, direct, no-resolve
IP-CIDR, 172.16.0.0/12, direct, no-resolve
IP-CIDR, 192.168.0.0/16, direct, no-resolve
IP-CIDR, 198.18.0.0/16, direct, no-resolve
IP-CIDR, 224.0.0.0/4, direct, no-resolve
IP6-CIDR, ::1/128, direct, no-resolve
IP6-CIDR, fc00::/7, direct, no-resolve
IP6-CIDR, fe80::/10, direct, no-resolve
IP6-CIDR, fd00::/8, direct, no-resolve

# 路由器管理域名
HOST, instant.arubanetworks.com, direct
HOST, setmeup.arubanetworks.com, direct
HOST, router.asus.com, direct
HOST, www.asusrouter.com, direct
HOST-SUFFIX, hiwifi.com, direct
HOST-SUFFIX, leike.cc, direct
HOST-SUFFIX, miwifi.com, direct
HOST-SUFFIX, my.router, direct
HOST-SUFFIX, p.to, direct
HOST-SUFFIX, peiluyou.com, direct
HOST-SUFFIX, phicomm.me, direct
HOST-SUFFIX, router.ctc, direct
HOST-SUFFIX, routerlogin.com, direct
HOST-SUFFIX, tendawifi.com, direct
HOST-SUFFIX, zte.home, direct
HOST-SUFFIX, tplogin.cn, direct
HOST-SUFFIX, wifi.cmcc, direct
