## 一些常用的直连设置

host, ad.12306.cn, direct
host, m.ctrip.com, direct
host, sdkapp.uve.weibo.com, direct
host-keyword, ultramobile, direct
host-suffix, edu.cn, direct

##银行设置
host, openapi.boc.cn, direct
host, mbs.boc.cn, direct
host, creditcardapp.bankcomm.cn, direct
##屏蔽农行vpn检测
host, msmp.abchina.com.cn, reject



host, combine.urbanairship.com, lisa
host, api.te-collinson.com, lisa
host-suffix, textnow.com, lisa

host, ocsp2.globalsign.com,lisa
host, cdn.jsdelivr.net,lisa
host, weather-analytics-events.apple.com,lisa
host, weather-data.apple.com,lisa
host, imeclient.openspeech.cn,lisa

##AI智能
host-suffix, apple-relay.apple.com,lisa 
host-suffix, apple-relay.fastly-edge.com,lisa 
host-suffix, apple-relay.cloudflare.com,lisa 
host-suffix, gateway.icloud.com,lisa 
host-suffix, guzzoni.apple.com,lisa 
host-suffix, cp4.cloudflare.com,lisa 
host-suffix, gspe1-ssl.ls.apple.com,lisa 
host-suffix, apps.mzstatic.com,lisa

#去掉YouTube++底部广告
host-suffix, ehg-youtube.hitbox.com, reject

# 屏蔽系统更新
host, ns.itunes.apple.com, reject
host, appldnld.apple.com, reject
host, mesu.apple.com, reject
host, xp.apple.com, reject
host, gdmf.apple.com, reject


# > 一些比较容易忽视的分流
host-keyword, github, lisa
host-suffix, fbcdn.net, lisa

host-keyword, imgur, lisa
host-keyword, v2ex, lisa


# > telegram相关配置
ip-cidr, 95.161.76.0/20, lisa
ip-cidr, 95.161.76.100/31, REJECT, no-resolve

