// == 苹果服务 (Apple) ==
// Apple CDN 加速
HOST-SUFFIX, cdn-apple.com, direct
// 苹果网络检测
HOST, captive.apple.com, direct

// == 腾讯系 (微信 / QQ / 腾讯地图) ==
// 微信支付
HOST-SUFFIX, wechatpay.cn, direct
// 微信国内节点加速
HOST, szextshort.weixin.qq.com, direct
// 微信香港与海外节点
HOST, hkshort.weixin.qq.com, direct
HOST, hklong.weixin.qq.com, direct
HOST, hkextshort.weixin.qq.com, direct
HOST, hkquic.weixin.qq.com, direct
// 微信 CDN 与静态资源 (头像、公众号图片、小程序资源)
HOST, wx.qlogo.cn, direct
HOST, res.wx.qq.com, direct
HOST-SUFFIX, mmbiz.qpic.cn, direct
HOST, vweixinthumb.tc.qq.com, direct
// 腾讯地图
HOST, lbs.map.qq.com, direct

// == 阿里系 (淘宝 / 支付宝 / CDN / 数据分析) ==
// 支付宝
HOST, amdc.alipay.com, direct
HOST, collect.alipay.com, direct
HOST-SUFFIX, alipay.hk, direct
// 淘宝
HOST, acs.m.taobao.com, direct
HOST, amdc.m.taobao.com, direct
HOST, guide-acs.m.taobao.com, direct
HOST, trade-acs.m.taobao.com, direct
HOST, audid-api.taobao.com, direct
HOST, fourier.taobao.com, direct
// 阿里 CDN & 静态资源
HOST, asearch.alicdn.com, direct
HOST, g.alicdn.com, direct
HOST, hudong.alicdn.com, direct
HOST, ilce.alicdn.com, direct
HOST, ossgw.alicdn.com, direct
// 阿里数据统计 (mmstat)
HOST, gm.mmstat.com, direct
HOST, d-gm.mmstat.com, direct
HOST, log.mmstat.com, direct
HOST, wgo.mmstat.com, direct
// 阿里妈妈广告联盟 (Tanx)
HOST, df.tanx.com, direct
HOST, ifs.tanx.com, direct

// == 百度系 ==
// 百度地图
HOST, loc.map.baidu.com, direct
HOST, newvector.map.baidu.com, direct

// == 美团系 ==
HOST, appsec-mobile.meituan.com, direct
HOST, api-unionid.meituan.com, direct

// == 其他国内常用 App ==
// 12306
HOST, ad.12306.cn, direct
// 携程
HOST, m.ctrip.com, direct
// 微博
HOST, sdkapp.uve.weibo.com, direct
// 哔哩哔哩 (Bilibili)
HOST, grpc.biliapi.net, direct
// 瑞幸咖啡
HOST, capi.lkcoffee.com, direct

// == 银行与金融机构 ==
// 中国银联 (云闪付)
HOST-SUFFIX, 95516.com, direct
// 中国银行
HOST, openapi.boc.cn, direct
HOST, mbs.boc.cn, direct
// 交通银行
HOST, creditcardapp.bankcomm.cn, direct

// == 系统基础服务 (网络检测 / NTP 时间 / 证书) ==
// 微软服务 & 时间
HOST, api.appcenter.ms, direct
HOST, client.wns.windows.com, direct
HOST, time.windows.com, direct
HOST, ntp.msn.com, direct
#HOST-SUFFIX, msftconnecttest.com, direct
#HOST-SUFFIX, microsoft.com, direct
// 证书验证
HOST, ocsp2.globalsign.com, direct
HOST, o.pki.goog, direct
// 火狐网络检测
HOST, detectportal.firefox.com, direct
// 开源 NTP 时间服务器
HOST-SUFFIX, pool.ntp.org, direct

// == 运营商与教育网 ==
// 中国教育网
HOST-SUFFIX, edu.cn, direct
// 台湾大哥大
HOST-SUFFIX, taiwanmobile.com, direct
// Ultra Mobile (PayGo)
HOST-KEYWORD, ultramobile, direct

// == 广告与追踪拦截 ==
// 腾讯微信数据统计/追踪
HOST-SUFFIX, wxs.qq.com, reject
